apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: college
  template:
    metadata:
      labels:
        app: college
    spec:
      containers:
      - name: college
        image: divya9866/python-ultimate-cicd:15
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
