apiVersion: apps/v1
kind: Deployment
metadata:
  name: collegeERP-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collegeERP
  template:
    metadata:
      labels:
        app: collegeERP
    spec:
      containers:
      - name: collegeERP
        image: divya9866/python-ultimate-cicd:15
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
